/// 插件列表
List<Map> plugins=[
	{
		"plugin_name":"flutter_staggered_animations",
		"title":"给列表，宫格等布局添加动画",
		"pub_url":"https://pub.flutter-io.cn/packages/flutter_staggered_animations",
		"routeName":"/flutter_staggered_animations"
	},
	{
		"plugin_name":"like_button",
		"title":"推特点赞效果带数量滚动动画",
		"pub_url":"https://pub.flutter-io.cn/packages/like_button",
		"routeName":"/like_button"
	},
	{
		"plugin_name":"flutter_swiper",
		"title":"flutter最强大的siwiper, 多种布局方式，无限轮播，Android和IOS双端适配",
		"pub_url":"https://pub.flutter-io.cn/packages/flutter_swiper",
		"routeName":"/flutter_swiper"
	},
	{
		"plugin_name":"photo_view",
		"title":"flutter图片放大预览查看器",
		"pub_url":"https://pub.flutter-io.cn/packages/photo_view",
		"routeName":"/photo_view"
	},
	{
		"plugin_name":"flutter_slidable",
		"title":"列表项左右滑动可带出按钮选项",
		"pub_url":"https://pub.flutter-io.cn/packages/flutter_slidable",
		"routeName":"/flutter_slidable"
	},
	{
		"plugin_name":"bot_toast",
		"title":"功能强大且无视context的toast提示",
		"pub_url":"https://pub.flutter-io.cn/packages/bot_toast",
		"routeName":"/bot_toast"
	},
	{
		"plugin_name":"percent_indicator",
		"title":"flutter圆形或线型进度条",
		"pub_url":"https://pub.flutter-io.cn/packages/percent_indicator",
		"routeName":"/percent_indicator"
	},
	{
		"plugin_name":"curved_navigation_bar",
		"title":"flutter一个超酷动画的底部tab栏",
		"pub_url":"https://pub.flutter-io.cn/packages/curved_navigation_bar",
		"routeName":"/curved_navigation_bar"
	},
	// {
	// 	"plugin_name":"image_cropper",
	// 	"title":"简单好用的图片裁剪组件",
	// 	"pub_url":"https://pub.flutter-io.cn/packages/image_cropper",
	// 	"routeName":"/image_cropper"
	// },
	{
		"plugin_name":"slide_up_panel",
		"title":"flutter可定制的上下滑出抽屉",
		"pub_url":"https://pub.flutter-io.cn/packages/slide_up_panel",
		"routeName":"/slide_up_panel"
	},
	{
		"plugin_name":"drag_list",
		"title":"flutter拖动排序元素",
		"pub_url":"https://pub.flutter-io.cn/packages/drag_list",
		"routeName":"/drag_list"
	},
	{
		"plugin_name":"animated_text_kit",
		"title":"flutter文字动效组件",
		"pub_url":"https://pub.flutter-io.cn/packages/animated_text_kit",
		"routeName":"/animated_text_kit"
	},
	{
		"plugin_name":"hidden_drawer_menu",
		"title":"flutter一个全屏动效的抽屉组件",
		"pub_url":"https://pub.flutter-io.cn/packages/hidden_drawer_menu",
		"routeName":"/hidden_drawer_menu"
	},
	{
		"plugin_name":"flutter_speed_dial",
		"title":"flutter可展开选项的浮动按钮",
		"pub_url":"https://pub.flutter-io.cn/packages/flutter_speed_dial",
		"routeName":"/flutter_speed_dial"
	},
	{
		"plugin_name":"flutter_custom_clippers",
		"title":"flutter将widget裁剪成各种自定义形状",
		"pub_url":"https://pub.flutter-io.cn/packages/flutter_custom_clippers",
		"routeName":"/flutter_custom_clippers"
	},
	
	{
		"plugin_name":"sticky_headers",
		"title":"flutter给滚动内容添加粘性header组件",
		"pub_url":"https://pub.flutter-io.cn/packages/sticky_headers",
		"routeName":"/sticky_headers"
	},
	{
		"plugin_name":"flutter_rating_bar",
		"title":"flutter可自定义的评分组件",
		"pub_url":"https://pub.flutter-io.cn/packages/flutter_rating_bar",
		"routeName":"/flutter_rating_bar"
	},
	{
		"plugin_name":"wave",
		"title":"flutter可自定义的波浪组件",
		"pub_url":"https://pub.flutter-io.cn/packages/wave",
		"routeName":"/wave"
	},
	{
		"plugin_name":"flip_card",
		"title":"flutter可翻转的卡片组件",
		"pub_url":"https://pub.flutter-io.cn/packages/flip_card",
		"routeName":"/flip_card"
	},
	{
		"plugin_name":"liquid_swipe",
		"title":"flutter液体效果的页面切换组件",
		"pub_url":"https://pub.flutter-io.cn/packages/liquid_swipe",
		"routeName":"/liquid_swipe"
	},
	{
		"plugin_name":"liquid_progress_indicator",
		"title":"flutter水波效果的进度器",
		"pub_url":"https://pub.flutter-io.cn/packages/liquid_progress_indicator",
		"routeName":"/liquid_progress_indicator"
	},
	{
		"plugin_name":"passcode_screen",
		"title":"flutter仿iPhone锁屏界面",
		"pub_url":"https://pub.flutter-io.cn/packages/passcode_screen",
		"routeName":"/passcode_screen"
	},
	{
		"plugin_name":"scratcher",
		"title":"flutter制作刮刮卡效果",
		"pub_url":"https://pub.flutter-io.cn/packages/scratcher",
		"routeName":"/scratcher"
	},
];